[package]
name = "neofoodclub"
version = "1.0.4"
edition = "2021"

[lib]
name = "neofoodclub"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module", "abi3-py38"] }
neofoodclub = { path = "./neofoodclub_rs" }
chrono = "0.4.35"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
