[package]
name = "neofoodclub"
version = "0.0.1"
edition = "2021"

[lib]
name = "neofoodclub"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
numpy = "0.17.2"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
