[package]
name = "neofoodclub"
version = "0.0.6"
edition = "2021"

[lib]
name = "neofoodclub"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module", "abi3-py38"] }
numpy = "0.20.0"
neofoodclub = { path = "./neofoodclub_rs" }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
