[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.coverage.run]
relative_files = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@overload",
    '^ *\.\.\.$',
    "if (False|TYPE_CHECKING):",
    "def __repr__"
]

[tool.pyright]
include = [
    "neofoodclub",
]
exclude = [
    "**/__pycache__",
]
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "error"
pythonVersion = "3.10"
typeCheckingMode = "basic"

[tool.ruff]
show-fixes = true
target-version = "py310"

[tool.ruff.lint]
extend-select = [
    "C4",
    "SIM",
    "TCH",
    "UP",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN205",
    "ANN206",
]
ignore = ["E501", "F403"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
