name: Coverage

on:
  pull_request:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ github.token }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.22"

      - name: Set up Python
        run: uv python install 3.13

      - name: Installing distribution (dev mode)
        # this adds the .so to the inner lib files so we can test
        run: |
          uv run --no-project ./setup.py develop
      - name: Run tests
        shell: bash
        run: |
          uv venv
          uv pip install pytest coverage
          uv run --no-project coverage run -m pytest

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
