name: Tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    name: pytest ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ github.token }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        shell: bash
        run: |
          uv run --frozen pytest
